language: generic

sudo: required
services:
  - docker

before_install:
  - docker build  -t gmk/docker_react  -f Dockerfile.dev .

script:
  - docker run -e CI=true gmk/docker_react npm run test -- --coverage